EXCEPTION: Inside Exception Time_21 is a deprecated bug
Traceback (most recent call last):
  File "run.py", line 16, in task
    raise Exception('{} is a deprecated bug'.format(bug_id))
Exception: Time_21 is a deprecated bug

